version: '3.6'

services:
  web:
    environment:
      - APP_ENV=dev
      - IS_DDEV=true
      - IS_DDEV_PROJECT=true
      - TYPO3_CONTEXT=Development
      - WP_ENV=development
      - environment=ddev
      - DBGP_IDEKEY=PHPSTORM
      - PHP_IDE_CONFIG="serverName=local.ddev.site" /scripts/run-tests --class=MyClass
  db:
    environment:
      - ENVIRONMENT=ddev
      - APP=Development
      - DDEV_IMPORTDIR=../sql
