version: '3.7'

networks:
  default:
    name: ddev_default

volumes:
  webgoat:

services:

  webgoat:
    container_name: ddev-${DDEV_SITENAME}-webgoat
    image: webgoat/webgoat-8.0
    restart: on-failure
    mem_limit: 200m
    cpus: 0.5
    ports:
      - 8186:8080
    volumes:
      - webgoat:/var/www/

