version: '3.6'

services:
  web:
    volumes:
      - "./../public/:/var/www/html/"
      - "./../logs/:/var/log/apache2/"
      - "./pi.php:/var/www/html/pi.php"
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  db:
    volumes:
      - "./sql/:/sql/"
